<section class="about-container">
    <h2>Desarrolladores:</h2>

    <div class="about-tarjeta">
        <h3>Valentina Zunino</h3>
        <h4>Email de contacto: <a href="https://mail.google.com/" target="_blank" class="gmail-link">zuninov9@gmail.com</a></h4>
    </div>

    <div class="about-tarjeta">
        <h3>Facundo Bravo</h3>
        <h4>Email de contacto: <a href="https://mail.google.com/" target="_blank" class="gmail-link">bfacundo176@gmail.com</a></h4>
    </div>
</section>