<section class="form-container">
    <form class="form" method="POST" action="nuevoLibro">
        <input class="input" type="text" name="titulo" placeholder="Titulo" required>
        <input class="input" type="text" name="genero" placeholder="Genero" required>
        <input class="input" type="text" name="descripcion" placeholder="Descripcion" required>
        <input class="input" type="number" name="precio" placeholder="Precio" required>

        <label for="autor">Autor</label>
        <select class="input select" name="autor" id="selectAutor">
            <?php foreach ($autores as $autor) : ?>
                <option value="<?= $autor->id ?>"><?= $autor->nombre ?></option>
            <?php endforeach ?>
            <option value="otro">Otro</option>
        </select>

        <input class="oculto input" type="text" id="nombreAutor" name="nombreAutor" placeholder="Nombre">
        <input class="oculto input" type="text" id="descripcionAutor" name="descripcionAutor" placeholder="Descripcion">

        <button class="boton">Cargar</button>
    </form>

    <div class="mensaje-contenedor">
        <h4><?= $mensaje ?></h4>
    </div>
</section>