    </main>
    
    <footer>
        <div>
            <p>Contactanos:</p>
            <a href="https://mail.google.com/" target="_blank" class="gmail-link">zuninov9@gmail.com</a>
            <a href="https://mail.google.com/" target="_blank" class="gmail-link">bfacundo176@gmail.com</a>
        </div>
    </footer>
    
    <?php if ($_GET["action"] == "cargarLibro" || $_GET["action"] == "nuevoLibro") : ?>
        <script src="js/jsForm.js"></script>
    <?php endif ?>
</body>
</html>