<article>
    <form class="form" method="POST" action="<?= $action ?>">
        <input type="text" name="usuario" placeholder="Usuario" required autocomplete="off">
        <input type="password" name="contrasenia" placeholder="Contraseña" required>

        <?php if ($_GET['action'] == 'registro' || $_GET['action'] == 'nuevoUsuario') : ?>
            <button class="boton">Registrarse</button>
        <?php else : ?>
            <button class="boton">Ingresar</button>
        <?php endif ?>
    </form>

    <div class="mensaje-contenedor">
        <h4><?= $mensaje ?></h4>
    </div>
</article>