<!DOCTYPE html>
<html lang="es">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="CSS/inicio.css">
    <title><?= $titulo ?></title>
</head>
<body>
    <header>
        <h1><?= $titulo ?></h1>

        <nav>
            <ul id="inicio" >
                <li class="boton"><a class="linkInvisible" >Autores</a></li>
                <li class="boton"><a class="linkInvisible" >Libros</a></li>
                <li class="boton"><a class="linkInvisible" >Contacto</a></li> 
                <!-- Agregar contacto -->
            </ul>

            <a href="login">Iniciar Sesion</a>
        </nav>
    </header>
