<!DOCTYPE html>
<html lang="es">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="CSS/inicio.css">
    <title><?= $titulo ?></title>
</head>
<body>
    <header>
        <div>
            <h1><?= $titulo ?></h1>
            <?php if ($_SESSION['logueado']) : ?>
                <a href="logout" class="boton">Cerrar Sesion</a>
            <?php else : ?>
                <a href="login" class="boton">Iniciar Sesion</a>
            <?php endif ?>
        </div>

        <nav>
            <ul>
                <li><a href="home" class="boton">Home</a></li>
                <li><a href="autores" class="boton">Autores</a></li>
                <li><a href="contacto" class="boton">Contacto</a></li>
                <!-- Agregar contacto -->
            </ul>
        </nav>
    </header>