<!DOCTYPE html>
<html lang="es">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/inicio.css">
    <title><?= $titulo ?></title>
</head>
<body>
    <header>
        <div>
            <h1><?= $titulo ?></h1>

            <?php if (!isset($_SESSION['USER_ID'])) : ?>
                <?php if ($_GET["action"] == "login" || $_GET["action"] == "auth") : ?>
                    <a href="registro" class="boton">Registrarse</a>
                <?php else : ?>
                    <a href="login" class="boton">Iniciar Sesion</a>
                <?php endif ?>
            <?php else : ?>
                <a href="logout" class="boton">Cerrar Sesion</a>
            <?php endif ?>
        </div>

        <nav>
            <ul>
                <li><a href="home" class="boton">Home</a></li>
                <li><a href="autores" class="boton">Autores</a></li>

                <?php if (isset($_SESSION['USER_ID']) && $_SESSION["USER_ROL"] == "administrador") : ?>
                    <li><a href="cargarLibro" class="boton">Cargar Libro</a></li>
                <?php endif ?>

                <li><a href="about" class="boton">About</a></li>
            </ul>
        </nav>
    </header>
    
    <main>