<section class="libro-info-container">
    <article>
        <div>
            <h3>Descripción:</h3>
            <p><?= $libro->descripcion ?></p>
        </div>

        <div>
            <h3>Información:</h3>
            <p>Género: <?= $libro->genero ?></p>
            <p>Autor: <a href="autor/<?= $autor->id ?>"><?= $autor->nombre ?></a></p>
            <p>$<?= $libro->precio ?></p>
        </div>
    </article>
</section>